# Generated by Django 4.2.7 on 2023-11-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0005_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='time',
        ),
        migrations.AddField(
            model_name='machine',
            name='area',
            field=models.CharField(default='', max_length=100, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine',
            field=models.CharField(default='', max_length=100, verbose_name='机器名'),
        ),
    ]
