# Generated by Django 4.2.7 on 2023-12-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0008_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名')),
                ('phone', models.CharField(max_length=100, verbose_name='电话')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('qq', models.CharField(max_length=100, verbose_name='QQ')),
                ('wechat', models.CharField(max_length=100, verbose_name='微信')),
            ],
        ),
    ]
