# Generated by Django 4.2.7 on 2023-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0015_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='img',
        ),
    ]
