# Generated by Django 4.2.10 on 2024-03-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0018_cxlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.CharField(max_length=100, verbose_name='商品价格')),
                ('goodstype', models.CharField(max_length=100, verbose_name='商品类型')),
                ('image', models.CharField(max_length=100, verbose_name='商品图片')),
                ('goodsdesc', models.CharField(max_length=1000, verbose_name='商品描述')),
            ],
        ),
    ]
