# Generated by Django 4.2.10 on 2024-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0019_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300, verbose_name='敏感词')),
            ],
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Cxlist',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='example',
        ),
        migrations.DeleteModel(
            name='machine',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
