# Generated by Django 4.2.10 on 2024-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0021_remove_goods_goodstype_goods_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100, verbose_name='订单编号')),
                ('userid', models.CharField(max_length=100, verbose_name='用户编号')),
                ('goodsid', models.CharField(max_length=100, verbose_name='商品编号')),
                ('goodsname', models.CharField(max_length=100, verbose_name='商品名称')),
                ('goodsnum', models.CharField(max_length=100, verbose_name='商品数量')),
                ('goodsprice', models.CharField(max_length=100, verbose_name='商品价格')),
                ('fee', models.CharField(max_length=100, verbose_name='运费')),
                ('total', models.CharField(max_length=100, verbose_name='总价')),
                ('ordertime', models.CharField(max_length=100, verbose_name='下单时间')),
                ('orderstatus', models.CharField(max_length=100, verbose_name='订单状态')),
            ],
        ),
    ]
