# Generated by Django 4.2.7 on 2023-11-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=100, verbose_name='性别')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
            ],
        ),
    ]
