# Generated by Django 2.1.14 on 2023-11-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0002_auto_20231114_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogdoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='博客名')),
                ('content', models.TextField(verbose_name='博客内容')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('category', models.CharField(max_length=100, verbose_name='博客分类')),
                ('image', models.FileField(max_length=300, upload_to='blog/images/', verbose_name='博客图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywb.User')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('blogdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywb.Blogdoc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywb.User')),
            ],
        ),
    ]
