# Generated by Django 4.2.7 on 2023-12-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0007_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
            ],
        ),
    ]
