# Generated by Django 4.2.7 on 2023-12-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0009_shopinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商户名')),
                ('phone', models.CharField(max_length=100, verbose_name='电话')),
                ('jylx', models.CharField(max_length=100, verbose_name='经营类型')),
                ('level', models.CharField(max_length=100, verbose_name='商户级别')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
            ],
        ),
    ]
