# Generated by Django 4.2.7 on 2023-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0011_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='缴费编号')),
                ('merchant', models.CharField(max_length=100, verbose_name='缴费商户')),
                ('title', models.CharField(max_length=100, verbose_name='缴费名称')),
                ('money', models.CharField(max_length=100, verbose_name='缴费金额')),
                ('status', models.CharField(max_length=100, verbose_name='缴费状态')),
                ('create_time', models.CharField(max_length=100, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='促销编号')),
                ('title', models.CharField(max_length=100, verbose_name='促销名称')),
                ('address', models.CharField(max_length=100, verbose_name='促销地点')),
                ('start_time', models.CharField(max_length=100, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=100, verbose_name='结束时间')),
                ('money', models.CharField(max_length=100, verbose_name='促销金额')),
                ('status', models.CharField(max_length=100, verbose_name='促销状态')),
                ('create_time', models.CharField(max_length=100, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Publicmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='公告编号')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.CharField(max_length=100, verbose_name='公告内容')),
                ('status', models.CharField(max_length=100, verbose_name='公告状态')),
                ('expriy', models.IntegerField(max_length=100, verbose_name='公告过期时间')),
            ],
        ),
    ]
