# Generated by Django 4.2.7 on 2023-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0012_charge_promotion_publicmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='普通用户', max_length=100, verbose_name='角色'),
        ),
    ]
