# Generated by Django 4.2.7 on 2023-12-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0013_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
