# Generated by Django 4.2.7 on 2023-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0014_user_integral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='服务名称')),
                ('content', models.CharField(max_length=100, verbose_name='服务内容')),
                ('status', models.CharField(max_length=100, verbose_name='提供商户')),
                ('price', models.CharField(max_length=100, verbose_name='服务价格')),
                ('img', models.CharField(max_length=100, verbose_name='服务图片')),
            ],
        ),
    ]
