# Generated by Django 4.2.7 on 2023-12-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0017_device_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cxlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户')),
                ('cxname', models.CharField(max_length=100, verbose_name='活动名称')),
                ('cxstarttime', models.CharField(max_length=100, verbose_name='参加时间')),
                ('status', models.CharField(max_length=100, verbose_name='活动状态')),
            ],
        ),
    ]
