# Generated by Django 4.2.7 on 2023-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0004_alter_blogdoc_id_alter_blogdoc_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=100, verbose_name='机器名')),
                ('time', models.DateTimeField(verbose_name='创建时间')),
                ('alarm', models.CharField(max_length=100, verbose_name='报警')),
            ],
        ),
    ]
