# Generated by Django 4.2.7 on 2023-12-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0016_remove_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicesn', models.CharField(max_length=100, verbose_name='设备编号')),
                ('devicename', models.CharField(max_length=100, verbose_name='设备名称')),
                ('devicetype', models.CharField(max_length=100, verbose_name='设备类型')),
                ('devicestatus', models.CharField(max_length=100, verbose_name='设备状态')),
                ('devicetime', models.CharField(max_length=100, verbose_name='设备时间')),
                ('deviceaddress', models.CharField(max_length=100, verbose_name='所在位置')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicletype', models.CharField(max_length=100, verbose_name='车辆类型')),
                ('Vehiclenum', models.CharField(max_length=100, verbose_name='车辆号码')),
                ('Parkingtime', models.CharField(max_length=100, verbose_name='停车时间')),
                ('Parkingfee', models.CharField(max_length=100, verbose_name='停车费用')),
                ('entrytime', models.CharField(max_length=100, verbose_name='入场时间')),
                ('exittime', models.CharField(max_length=100, verbose_name='出场时间')),
                ('status', models.CharField(max_length=100, verbose_name='停车状态')),
            ],
        ),
    ]
