# Generated by Django 4.2.10 on 2024-04-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0020_sensitive_delete_charge_delete_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goodstype',
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mywb.category', verbose_name='商品分类'),
        ),
    ]
