# Generated by Django 4.2.10 on 2024-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0022_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
