# Generated by Django 4.2.10 on 2024-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0023_rename_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='收货人电话'),
        ),
        migrations.AddField(
            model_name='orders',
            name='remark',
            field=models.CharField(default='', max_length=1000, verbose_name='备注'),
        ),
    ]
