# Generated by Django 4.2.7 on 2023-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywb', '0010_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='合同编号')),
                ('title', models.CharField(max_length=100, verbose_name='合同名称')),
                ('money', models.CharField(max_length=100, verbose_name='合同金额')),
                ('start_time', models.CharField(max_length=100, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=100, verbose_name='结束时间')),
                ('status', models.CharField(max_length=100, verbose_name='合同状态')),
                ('create_time', models.CharField(max_length=100, verbose_name='创建时间')),
                ('party1', models.CharField(max_length=100, verbose_name='甲方')),
                ('party2', models.CharField(max_length=100, verbose_name='乙方')),
                ('party3', models.CharField(max_length=100, verbose_name='丙方')),
                ('remarm', models.CharField(max_length=100, verbose_name='备注')),
            ],
        ),
    ]
