# Generated by Django 4.2.7 on 2023-12-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='', max_length=100, verbose_name='机器号')),
                ('time', models.DateTimeField(default='', max_length=100, verbose_name='时间')),
                ('alarm', models.CharField(default=0, max_length=500, verbose_name='报警')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='', max_length=100, verbose_name='机器号')),
                ('brand', models.CharField(default='', max_length=100, verbose_name='牌号')),
                ('output', models.IntegerField(default=0, max_length=100, verbose_name='产量')),
                ('speed', models.IntegerField(default=0, max_length=100, verbose_name='速度')),
                ('reject_count', models.IntegerField(default=0, max_length=100, verbose_name='剔除量')),
                ('reject_rate', models.FloatField(default=0, max_length=100, verbose_name='剔除率')),
                ('work_status', models.CharField(default='', max_length=100, verbose_name='工作状态')),
                ('reject_status', models.CharField(default='', max_length=100, verbose_name='剔除状态')),
                ('system_status', models.CharField(default='', max_length=100, verbose_name='系统状态')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='', max_length=100, verbose_name='机器名')),
                ('area', models.CharField(default='', max_length=100, verbose_name='区域')),
            ],
        ),
        migrations.CreateModel(
            name='reject_module1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(default='', max_length=100, verbose_name='机器号')),
                ('reject', models.CharField(default='', max_length=100, verbose_name='定位')),
                ('count', models.IntegerField(default=0, max_length=100, verbose_name='统计数')),
            ],
        ),
        migrations.CreateModel(
            name='reject_module2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(default='', max_length=100, verbose_name='机器号')),
                ('reject', models.CharField(default='', max_length=100, verbose_name='定位')),
                ('count', models.IntegerField(default=0, max_length=100, verbose_name='统计数')),
            ],
        ),
    ]
